/**
 * @file SRParticleTruthDLP.cxx
 * @brief Implementation of the SRParticleTruthDLP class.
 * @author mueller@fnal.gov
 */
#include <limits>
#include <vector>
#include "SRParticleTruthDLP.h"

namespace caf
{
    SRParticleTruthDLP::SRParticleTruthDLP():
        ancestor_creation_process(),
        ancestor_pdg_code(std::numeric_limits<int64_t>::signaling_NaN()),
        ancestor_position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        ancestor_t(std::numeric_limits<double>::signaling_NaN()),
        ancestor_track_id(std::numeric_limits<int64_t>::signaling_NaN()),
        calo_ke(-1.0),
        cathode_offset(std::numeric_limits<double>::signaling_NaN()),
        children_counts(std::vector<int64_t>()),
        children_id(std::vector<int64_t>()),
        csda_ke(std::numeric_limits<double>::signaling_NaN()),
        csda_ke_per_pid{std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN()},
        depositions_adapt_q_sum(std::numeric_limits<float>::signaling_NaN()),
        depositions_adapt_sum(std::numeric_limits<float>::signaling_NaN()),
        depositions_g4_sum(std::numeric_limits<int64_t>::signaling_NaN()),
        depositions_q_sum(std::numeric_limits<float>::signaling_NaN()),
        depositions_sum(std::numeric_limits<float>::signaling_NaN()),
        distance_travel(std::numeric_limits<double>::signaling_NaN()),
        end_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_momentum{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_p(std::numeric_limits<float>::signaling_NaN()),
        end_point{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_t(std::numeric_limits<double>::signaling_NaN()),
        energy_deposit(std::numeric_limits<double>::signaling_NaN()),
        energy_init(std::numeric_limits<double>::signaling_NaN()),
        first_step{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        fragment_ids(std::vector<int32_t>()),
        group_id(std::numeric_limits<int64_t>::signaling_NaN()),
        group_primary(std::numeric_limits<int64_t>::signaling_NaN()),
        id(std::numeric_limits<int64_t>::signaling_NaN()),
        interaction_id(std::numeric_limits<int64_t>::signaling_NaN()),
        interaction_primary(std::numeric_limits<int64_t>::signaling_NaN()),
        is_cathode_crosser(false),
        is_contained(false),
        is_matched(false),
        is_primary(false),
        is_time_contained(true),
        is_truth(false),
        is_valid(false),
        ke(std::numeric_limits<double>::signaling_NaN()),
        last_step{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        length(std::numeric_limits<double>::signaling_NaN()),
        mass(std::numeric_limits<double>::signaling_NaN()),
        match_ids(std::vector<int64_t>()),
        match_overlaps(std::vector<float>()),
        mcs_ke(std::numeric_limits<double>::signaling_NaN()),
        mcs_ke_per_pid{std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN()},
        mcst_index(std::numeric_limits<int64_t>::signaling_NaN()),
        mct_index(std::numeric_limits<int64_t>::signaling_NaN()),
        module_ids(std::vector<int64_t>()),
        momentum{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        nu_id(std::numeric_limits<int64_t>::signaling_NaN()),
        num_fragments(std::numeric_limits<int64_t>::signaling_NaN()),
        num_voxels(std::numeric_limits<int64_t>::signaling_NaN()),
        orig_children_id(std::vector<int64_t>()),
        orig_group_id(std::numeric_limits<int64_t>::signaling_NaN()),
        orig_id(std::numeric_limits<int64_t>::signaling_NaN()),
        orig_interaction_id(std::numeric_limits<int64_t>::signaling_NaN()),
        orig_parent_id(std::numeric_limits<int64_t>::signaling_NaN()),
        p(std::numeric_limits<double>::signaling_NaN()),
        parent_creation_process(),
        parent_id(std::numeric_limits<int64_t>::signaling_NaN()),
        parent_pdg_code(std::numeric_limits<int64_t>::signaling_NaN()),
        parent_position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        parent_t(std::numeric_limits<double>::signaling_NaN()),
        parent_track_id(std::numeric_limits<int64_t>::signaling_NaN()),
        pdg_code(std::numeric_limits<int64_t>::signaling_NaN()),
        pid((int64_t)-1),
        position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        reco_end_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        reco_ke(std::numeric_limits<double>::signaling_NaN()),
        reco_length(std::numeric_limits<double>::signaling_NaN()),
        reco_momentum{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        reco_start_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        shape((int64_t)-1),
        size(std::numeric_limits<int64_t>::signaling_NaN()),
        size_adapt(std::numeric_limits<int64_t>::signaling_NaN()),
        size_g4(std::numeric_limits<int64_t>::signaling_NaN()),
        start_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        start_point{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        t(std::numeric_limits<double>::signaling_NaN()),
        track_id(std::numeric_limits<int64_t>::signaling_NaN()),
        units() { }

    SRParticleTruthDLP::~SRParticleTruthDLP() { }
} // namespace caf