/**
 * @file SRParticleTruthDLP.cxx
 * @brief Implementation of the SRParticleTruthDLP class.
 * @author mueller@fnal.gov
 */
#include <limits>
#include <vector>
#include "sbnanaobj/StandardRecord/SRConstants.h"

namespace caf
{
    SRParticleTruthDLP::SRParticleTruthDLP():
        ancestor_creation_process(),
        ancestor_pdg_code(caf::kUninitializedInt),
        ancestor_position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        ancestor_t(std::numeric_limits<double>::signaling_NaN()),
        ancestor_track_id(caf::kUninitializedInt),
        calo_ke(std::numeric_limits<double>::signaling_NaN()),
        cathode_offset(std::numeric_limits<double>::signaling_NaN()),
        children_counts(),
        children_id(),
        csda_ke(std::numeric_limits<double>::signaling_NaN()),
        csda_ke_per_pid{std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN()},
        depositions_adapt_q_sum(std::numeric_limits<float>::signaling_NaN()),
        depositions_adapt_sum(std::numeric_limits<float>::signaling_NaN()),
        depositions_g4_sum(caf::kUninitializedInt),
        depositions_q_sum(std::numeric_limits<float>::signaling_NaN()),
        depositions_sum(std::numeric_limits<float>::signaling_NaN()),
        distance_travel(std::numeric_limits<double>::signaling_NaN()),
        end_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_momentum{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_p(std::numeric_limits<float>::signaling_NaN()),
        end_point{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        end_t(std::numeric_limits<double>::signaling_NaN()),
        energy_deposit(std::numeric_limits<double>::signaling_NaN()),
        energy_init(std::numeric_limits<double>::signaling_NaN()),
        first_step{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        fragment_ids(),
        group_id(caf::kUninitializedInt),
        group_primary(caf::kUninitializedInt),
        id(caf::kUninitializedInt),
        interaction_id(caf::kUninitializedInt),
        interaction_primary(caf::kUninitializedInt),
        is_cathode_crosser(false),
        is_contained(false),
        is_matched(false),
        is_primary(false),
        is_time_contained(true),
        is_truth(false),
        is_valid(false),
        ke(std::numeric_limits<double>::signaling_NaN()),
        last_step{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        length(std::numeric_limits<double>::signaling_NaN()),
        mass(std::numeric_limits<double>::signaling_NaN()),
        match_ids(),
        match_overlaps(std::vector<float>()),
        mcs_ke(std::numeric_limits<double>::signaling_NaN()),
        mcs_ke_per_pid{std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN(), std::numeric_limits<double>::signaling_NaN()},
        mcst_index(caf::kUninitializedInt),
        mct_index(caf::kUninitializedInt),
        module_ids(),
        momentum{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        nu_id(caf::kUninitializedInt),
        num_fragments(caf::kUninitializedInt),
        num_voxels(caf::kUninitializedInt),
        orig_children_id(),
        orig_group_id(caf::kUninitializedInt),
        orig_id(caf::kUninitializedInt),
        orig_interaction_id(caf::kUninitializedInt),
        orig_parent_id(caf::kUninitializedInt),
        p(std::numeric_limits<double>::signaling_NaN()),
        parent_creation_process(),
        parent_id(caf::kUninitializedInt),
        parent_pdg_code(caf::kUninitializedInt),
        parent_position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        parent_t(std::numeric_limits<double>::signaling_NaN()),
        parent_track_id(caf::kUninitializedInt),
        pdg_code(caf::kUninitializedInt),
        pid(caf::kUninitializedInt)
        position{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        reco_end_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        reco_ke(std::numeric_limits<double>::signaling_NaN()),
        reco_length(std::numeric_limits<double>::signaling_NaN()),
        reco_momentum{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        reco_start_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        shape(caf::kUninitializedInt),
        size(caf::kUninitializedInt),
        size_adapt(caf::kUninitializedInt),
        size_g4(caf::kUninitializedInt),
        start_dir{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        start_point{std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN(), std::numeric_limits<float>::signaling_NaN()},
        t(std::numeric_limits<double>::signaling_NaN()),
        track_id(caf::kUninitializedInt),
        units() { }

    SRParticleTruthDLP::~SRParticleTruthDLP() { }
} // namespace caf