/**
 * @file SRParticleTruthDLP.cxx
 * @brief Implementation of the SRParticleTruthDLP class.
 * @author mueller@fnal.gov
 */
#include <limits>
#include <vector>
#include "sbnanaobj/StandardRecord/SRConstants.h"
#include "sbnanaobj/StandardRecord/SRParticleTruthDLP.h"

namespace caf
{
    SRParticleTruthDLP::SRParticleTruthDLP():
        ancestor_creation_process(),
        ancestor_pdg_code(caf::kUninitializedInt),
        ancestor_position{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        ancestor_t(caf::kSignalingNaN),
        ancestor_track_id(caf::kUninitializedInt),
        calo_ke(caf::kSignalingNaN),
        cathode_offset(caf::kSignalingNaN),
        children_counts(),
        children_id(),
        csda_ke(caf::kSignalingNaN),
        csda_ke_per_pid{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        depositions_adapt_q_sum(caf::kSignalingNaN),
        depositions_adapt_sum(caf::kSignalingNaN),
        depositions_g4_sum(caf::kSignalingNaN),
        depositions_q_sum(caf::kSignalingNaN),
        depositions_sum(caf::kSignalingNaN),
        distance_travel(caf::kSignalingNaN),
        end_dir{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        end_momentum{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        end_p(caf::kSignalingNaN),
        end_point{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        end_position{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        end_t(caf::kSignalingNaN),
        energy_deposit(caf::kSignalingNaN),
        energy_init(caf::kSignalingNaN),
        first_step{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        fragment_ids(),
        group_id(caf::kUninitializedInt),
        group_primary(caf::kUninitializedInt),
        id(caf::kUninitializedInt),
        interaction_id(caf::kUninitializedInt),
        interaction_primary(caf::kUninitializedInt),
        is_cathode_crosser(false),
        is_contained(false),
        is_matched(false),
        is_primary(false),
        is_time_contained(true),
        is_truth(false),
        is_valid(false),
        ke(caf::kSignalingNaN),
        last_step{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        length(caf::kSignalingNaN),
        mass(caf::kSignalingNaN),
        match_ids(),
        match_overlaps(),
        mcs_ke(caf::kSignalingNaN),
        mcs_ke_per_pid{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        mcst_index(caf::kUninitializedInt),
        mct_index(caf::kUninitializedInt),
        module_ids(),
        momentum{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        nu_id(caf::kUninitializedInt),
        num_fragments(caf::kUninitializedInt),
        num_voxels(caf::kUninitializedInt),
        orig_children_id(),
        orig_group_id(caf::kUninitializedInt),
        orig_id(caf::kUninitializedInt),
        orig_interaction_id(caf::kUninitializedInt),
        orig_parent_id(caf::kUninitializedInt),
        p(caf::kSignalingNaN),
        parent_creation_process(),
        parent_id(caf::kUninitializedInt),
        parent_pdg_code(caf::kUninitializedInt),
        parent_position{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        parent_t(caf::kSignalingNaN),
        parent_track_id(caf::kUninitializedInt),
        pdg_code(caf::kUninitializedInt),
        pid(caf::kUninitializedInt),
        position{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        reco_end_dir{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        reco_ke(caf::kSignalingNaN),
        reco_length(caf::kSignalingNaN),
        reco_momentum{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        reco_start_dir{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        shape(caf::kUninitializedInt),
        size(caf::kUninitializedInt),
        size_adapt(caf::kUninitializedInt),
        size_g4(caf::kUninitializedInt),
        start_dir{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        start_point{caf::kSignalingNaN, caf::kSignalingNaN, caf::kSignalingNaN},
        t(caf::kSignalingNaN),
        track_id(caf::kUninitializedInt) { }
} // namespace caf